config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'prototypes/index'
  root to: "prototypes#index"
  # 2020/12/28 add S.Shimada
  # resourcesを用いて、上記で設定したnewアクションとcreateアクションに対するルーティングをroutes.rbに記述した。
  # resources :prototypes, only: [:new, :create,]
  # showアクションのルーティングを設定
  # resources :prototypes, only: [:new, :create, :show]
  # edit、updateアクションのルーティングを設定
  # resources :prototypes, only: [:new, :create, :show, :edit, :update]
  # 削除機能用のルーティングを設定
  # resources :prototypes, only: [:new, :create, :show, :edit, :update, :destroy]
  # //2020/12/28 add S.Shimada

  # 2020/12/29 add S.Shimada コメント機能のルーティングを設定
  resources :prototypes, only: [:new, :create, :show, :edit, :update, :destroy] do
    # doとendで挟むことにより、ルーティングの記述をネストさせることができました。
    # この記述によって、「ある投稿に対してのコメント」という親子関係を表現したパスが、
    # コメント投稿に必要なリクエストのパスになります。
    resources :comments, only: :create
    # いいね機能実装用のルーティング
    resources :likes, only: [:create, :destroy]
    # 検索機能の実装
    collection do
      get 'search'
    end
  end
  # //2020/12/29 add S.Shimada コメント機能のルーティングを設定

  # 2020/12/29 add S.Shimada ユーザーに関するshowアクションのルーティングを設定
  # My-carDページ用に追加
  resources :users, only: [:new, :edit, :show]
  # //2020/12/29 add S.Shimada ユーザーに関するshowアクションのルーティングを設定

  # 2020/12/25 add S.Shimada【解決策】deviseのログアウト機能でのエラー
  # routesが合っていないのが原因なので、書き換えないといけない。
  # 以下のコードを追加する。このコードは既存のログアウトルーティングに上書きされる。
  # ※application.html.erb側の変更は特になし
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # //2020/12/25 add S.Shimada【解決策】deviseのログアウト機能でのエラー
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  # 2020/12/29 add S.Shimada
  # ログインしていない状態だと特定のページへのアクセスが制限され、
  # ログインページにリダイレクトする
  before_action :authenticate_user!
  # //2020/12/29 add S.Shimada
  before_action :current_user_like_count
  # 2020/12/29 add S.Shimada アクセス制御1-1
  before_action :move_to_index, only: [:edit]
  # //2020/12/29 add S.Shimada アクセス制御1-1

  def index
    # 2020/12/28 add S.Shimada 03
    # indexアクションに、インスタンス変数@prototypesを定義し、すべてのプロトタイプの情報を代入した
    # @prototypes = Prototype.all
    # N+1問題の対応
    @prototypes = Prototype.includes(:user).order("created_at DESC")
    # //2020/12/28 add S.Shimada 03
    # PVカウントの追加実装
    # prototypes一覧をPV数の多い順に並び替える。
    @rank_prototypes = Prototype.order(impressions_count: 'DESC') # ソート機能を追加
    # //PVカウントの追加実装
  end
  # 2020/12/28 add S.Shimada 01
  def new
    # newアクションにインスタンス変数@prototypeを定義し、Prototypeモデルの新規オブジェクトを代入した
    @prototype = Prototype.new
  end

  def create
    @prototype = Prototype.create(prototype_params)
    if @prototype.save
      # createアクションにデータ保存のための記述をし、保存されたときはルートパスに戻るような記述をした
      redirect_to root_path
    else
      # createアクションに、データが保存されなかったときは新規投稿ページへ戻るようrenderを用いて記述した
      render :new
    end
  end
  # //2020/12/28 add S.Shimada 01

  # 2020/12/28 add S.Shimada 03
  def show
    # showアクションにインスタンス変数@prototypeを定義した。且つ、Pathパラメータで送信されるID値で、
    # Prototypeモデルの特定のオブジェクトを取得するように記述し、それを@prototypeに代入した
    @prototype = Prototype.find(params[:id])
    # 2020/12/29 add S.Shimada
    # prototypes/show.html.erbでform_withを使用して、comments#createを実行するリクエストを飛ばしたいので、
    # @comment = Comment.newというインスタンス変数を生成しておかないといけません。
    # prototypesテーブルとcommentsテーブルはアソシエーションが組まれているので、
    # @prototype.commentsとすることで、@prototypeへ投稿されたすべてのコメントを取得できます。
    @comment = Comment.new
    @comments = @prototype.comments.includes(:user).order("created_at DESC")
    # //2020/12/29 add S.Shimada
    # PVカウントの追加実装
    # ip_address：IPアドレス単位でカウント
    # session_hash：ユーザー別に詳細にアクセスするたびにカウント
    # impressionist(@prototype, nil, unique: [:ip_address]) 
    impressionist(@prototype, nil, unique: [:session_hash]) 
    # //PVカウントの追加実装
    
    # いいね機能実装用
    @like = Like.new
  end
  # //2020/12/28 add S.Shimada 03
  # 2020/12/28 add S.Shimada 04 edit updateを追加（編集機能）
  def edit
    @prototype = Prototype.find(params[:id])
  end
  # このupdateアクションも、destroyアクションと同様に、
  # ＠→インスタンス変数にしないと判定文が正常に動作しない。
  def update
    @prototype = Prototype.find(params[:id])
    if @prototype.update(prototype_params)
      # 詳細画面に遷移
      redirect_to prototype_path(@prototype.id)
    else
      # 空欄があると編集画面にとどまる。
      render :edit
    end
  end
  # //2020/12/28 add S.Shimada 04
  # 2020/12/28 add S.Shimada 05 削除機能
  def destroy
    prototype = Prototype.find(params[:id])
    prototype.destroy
    redirect_to root_path
  end
  # //2020/12/28 add S.Shimada 05
  # 検索機能実装
  def search
    @prototypes_search = Prototype.search(params[:keyword])
  end
  # //検索機能実装
  
  # 2020/12/28 add S.Shimada 02
  private
  def prototype_params
    # prototypesコントローラーのprivateメソッドにストロングパラメーターをセットし、
    # 特定の値のみを受け付けるようにした。且つ、user_idもmergeした
    # item=音声ファイル、genre_id=カテゴリーの追加
    params.require(:prototype).permit( :title, :catch_copy, :concept, :image, :item, :category_id).merge(user_id: current_user.id)
  end
  # //2020/12/28 add S.Shimada 02
  # 2020/12/29 add S.Shimada アクセス制御1-2
  def move_to_index
    prototype = Prototype.find(params[:id])
    unless user_signed_in? && current_user.id == prototype.user_id
      redirect_to action: :index
    end
  end
  # //2020/12/29 add S.Shimada アクセス制御1-2

  def current_user_like_count
    # ヘッダーのお気に入り枚数表示用
    if user_signed_in?
      @current_user_like_count = User.find(current_user.id)
    end
  end
end

app/helpers/prototypes_helper.rb
module PrototypesHelper
end

app/views/prototypes/_form.html.erb
<%#= form_with local: true do |f|%>
<%= form_with(model: prototype, local: true) do |f|%>
  <%= render 'shared/error_messages', model: prototype %>
  <div class="field">
    <%= f.label :title, "タイトル" %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :category_id, "カテゴリー" %><br />
    <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"category-select"}) %>
  </div>
  <div class="field">
    <%= f.label :catch_copy, "メッセージ" %><br />
    <%= f.text_area :catch_copy, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :concept, "音声読み上げ文章（※非表示）" %><br />
    <%= f.text_area :concept, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :image, "サムネイル" %><br />
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :item, "音声ファイル" %><br />
    <%= f.file_field :item %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/prototypes/_prototype.html.erb
<%= link_to prototype_path(prototype.id) do %>
  <%# カテゴリー別にカードの色を変える %>
  <% if prototype.category_id == 2 %>
    <li class='list card_back card_color2'>
  <% elsif prototype.category_id == 3 %>
    <li class='list card_back card_color3'>
  <% elsif prototype.category_id == 6 %>
    <li class='list card_back card_color6'>
  <% elsif prototype.category_id == 9 %>
    <li class='list card_back card_color9'>
  <% else %>
    <li class='list card_back card_color'>
  <% end %>
  <%# //カテゴリー別にカードの色を変える %>
    <div class='item-img-content'>
      <%= image_tag prototype.image, class: "item-img" %>
    </div>
    <div class='item-info'>
      <div class='star-btn'>
        <%= "(#{I18n.l prototype.created_at, formats: :default})" %>
      </div>
      <p class='item-name'>
        <%= prototype.title %>
      </p>
      <p class='item-name'>
      <%= link_to "by #{prototype.user.name}", "/users/#{prototype.user.id}", class: :prototype__user %>
      </p>
      <div class='star-btn-top'>
        <%= image_tag "category.png", class:"star-icon" %>
        <span class='star-count-top'><%= prototype.category.name %></span>
      </div>
      <div class='item-price'>
        <div class='star-btn-top'>
          <%= image_tag "count.png", class:"star-icon" %>
          <span class='star-count-top'><%= prototype.impressions_count %></span>
        </div>
        <div class='star-btn-top'>
          <%= image_tag "good.png", class:"star-icon" %>
          <span class='star-count-top'><%= prototype.liked_users.count %></span>
        </div>
      </div>
    </div>
  </li>
<% end %>

app/views/prototypes/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">Voice--carD 編集</h2>
      <%# 部分テンプレートでフォームを表示する %>
      <%= render partial: "form", locals: { prototype: @prototype } %>
    </div>
  </div>
</div>

app/views/prototypes/index.html.erb
<main class="main">

  <div class="inner">
    <%# 商品一覧 %>
    <div class='item-contents'>
      <h2 class='card__img'><%= image_tag "title.png", class: :logo2 %></h2>
      <ul class='item-lists'>
        <%= render partial: "prototype", collection: @prototypes %>
      </ul>
    </div>
    <%# /商品一覧 %>
  </div>
</main>

app/views/prototypes/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">Voice--carD作成</h2>
        <%# 部分テンプレートでフォームを表示する %>
        <%= render partial: "form", locals: { prototype: @prototype } %>
    </div>
  </div>
</div>

app/views/prototypes/search.html.erb
<main class="main">

  <div class="inner">
    <%# 商品一覧 %>
    <div class='item-contents'>
      <h2 class="page-heading"><%= "「#{params[:keyword]}」の検索結果" %></h2>
      <ul class='item-lists'>
        <% @prototypes_search.each do |prototype| %>
        <%= render partial: "prototype", locals: { prototype: prototype } %>
        <% end %>
      </ul>
    </div>
    <%# /商品一覧 %>
  </div>
</main>

app/views/prototypes/show.html.erb
<%# 詳細画面遷移時にJSを用いて１回だけリロードする機能を追加 %>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script language="javascript">
  if ( location.search.indexOf("1") == -1 ) {
  setTimeout("_reload()",1);
  }
  function _reload() {
  location.href = location.href + "?1";
  }
</script>

<meta content="no-cache" name="turbolinks-cache-control">
<main class="main">
  <div class="inner"><br>
    <%# カテゴリー別にカードの色を変える %>
    <% if @prototype.category_id == 2 %>
      <div class="prototype__wrapper card_back card_color2">
    <% elsif @prototype.category_id == 3 %>
      <div class="prototype__wrapper card_back card_color3">
    <% elsif @prototype.category_id == 6 %>
      <div class="prototype__wrapper card_back card_color6">
    <% elsif @prototype.category_id == 9 %>
      <div class="prototype__wrapper card_back card_color9">
    <% else %>
      <div class="prototype__wrapper card_back card_color">
    <% end %>
    <%# //カテゴリー別にカードの色を変える %>
      <%# プロトタイプの投稿者とログインしているユーザーが同じであれば以下を表示する %>
      <div class="prototype__manage">
        <input type="button"  value="音声読み上げ" class="btn">
        <input type="button"  value="読み上げ停止" class="btn2">
      </div>
      <div class="prototype__detail">
      <% if @prototype.item.file == nil %>
            ※音声ファイルは投稿されていません。
        <% end %>
      </div>
      <div class="prototype__manage3">
        <%= "投稿日：#{I18n.l @prototype.created_at, formats: :default}" %>
      </div>
      <%# // プロトタイプの投稿者とログインしているユーザーが同じであれば上記を表示する %>
      <section id="speech">
      <div class="prototype__body">
        <div class="prototype__detail">
        <h1 class="clearText">タイトル。</h1>
          <p class="detail__title2">[<%= "#{@prototype.title}" %>]</p>
          <p class="detail__message">
          </p>
        </div>
        <div class="prototype__image">
          <%= image_tag @prototype.image %>
        </div>
        <div class="prototype__detail">
          <% if @prototype.item.file != nil %>
            <%= audio_tag(@prototype.item, :autoplay => true, :controls => true) %>
          <% end %>
        </div>
        <h1 class="clearText">っ。<%= "#{@prototype.concept}" %></h1>
        </section>
        <div class="prototype__detail">
          <div class="detail__title2">
            <p><%= simple_format(h(@prototype.catch_copy)) %></p>
          </div>
          <div class="prototype__manage4">
            <%= link_to "by #{@prototype.user.name}", "/users/#{@prototype.user.id}", class: :prototype__user %>
          </div>
          <br>
          <div class="prototype__hedding">
            <div class='prototype__btn2'>
              <%= image_tag "category.png", class:"star-icon" %>
              <span class='star-count'><%= @prototype.category.name %></span>
            </div>
            <div class='prototype__btn2'>
              <%= image_tag "count.png", class:"star-icon" %>
              <span class='star-count'><%= @prototype.impressions_count %></span>
            </div>
            <div class='prototype__btn2'>
              <%= image_tag "good.png", class:"star-icon" %>
              <span class='star-count'><%= @prototype.likes.count %></span>
              <% if current_user.already_liked?(@prototype) %>
                <%= button_to 'return><', prototype_like_path(@prototype), method: :delete ,class: :nav__btn2 %>
              <% else %>
                <%= button_to 'Get!!^^', prototype_likes_path(@prototype),class: :nav__btn2 %>
              <% end %>
            </div>
          </div>
          <br>
        </div>
      </div>
      <% if user_signed_in? && current_user.id == @prototype.user_id %>
            <div class="prototype__manage2">
              <%= link_to "編集する", edit_prototype_path(@prototype.id),method: :get,class: :nav__btn2 %>
              <%= link_to "削除する", prototype_path(@prototype.id), method: :delete,class: :nav__btn2, data: { confirm: '削除しますか？' } %>
            </div>
            <% end %>
      <div class="prototype__comments">
        <%# ログインしているユーザーには以下のコメント投稿フォームを表示する %>
        <% if user_signed_in? %>
          <%= form_with(model: [@prototype, @comment], local: true) do |f|%>
            <div class="field">
              <%= f.label :text, "コメント" %><br />
              <%= f.text_field :text %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :chat_btn  %>
            </div>
          <% end %> 
        <% end %>
        <%# // ログインしているユーザーには上記を表示する %>
        <ul class="comments_lists">
          <%# 投稿に紐づくコメントを一覧する処理を記述する %>
          <% @comments.each do |comment| %>
            <li class="comments_list">
              <strong><%= comment.text%></strong>
              <%= link_to "（#{comment.user.name}）", "/users/#{comment.user.id}", class: :comment_user %>
            </li>
          <% end %>
          <%# // 投稿に紐づくコメントを一覧する処理を記述する %>
        </ul>
      </div>
      <Br>
    </div>
  </div>
</main>