config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'prototypes/index'
  root to: "prototypes#index"
  # 2020/12/28 add S.Shimada
  # resourcesを用いて、上記で設定したnewアクションとcreateアクションに対するルーティングをroutes.rbに記述した。
  # resources :prototypes, only: [:new, :create,]
  # showアクションのルーティングを設定
  # resources :prototypes, only: [:new, :create, :show]
  # edit、updateアクションのルーティングを設定
  # resources :prototypes, only: [:new, :create, :show, :edit, :update]
  # 削除機能用のルーティングを設定
  # resources :prototypes, only: [:new, :create, :show, :edit, :update, :destroy]
  # //2020/12/28 add S.Shimada

  # 2020/12/29 add S.Shimada コメント機能のルーティングを設定
  resources :prototypes, only: [:new, :create, :show, :edit, :update, :destroy] do
    # doとendで挟むことにより、ルーティングの記述をネストさせることができました。
    # この記述によって、「ある投稿に対してのコメント」という親子関係を表現したパスが、
    # コメント投稿に必要なリクエストのパスになります。
    resources :comments, only: :create
    # いいね機能実装用のルーティング
    resources :likes, only: [:create, :destroy]
    # 検索機能の実装
    collection do
      get 'search'
    end
  end
  # //2020/12/29 add S.Shimada コメント機能のルーティングを設定

  # 2020/12/29 add S.Shimada ユーザーに関するshowアクションのルーティングを設定
  # My-carDページ用に追加
  resources :users, only: [:new, :edit, :show]
  # //2020/12/29 add S.Shimada ユーザーに関するshowアクションのルーティングを設定

  # 2020/12/25 add S.Shimada【解決策】deviseのログアウト機能でのエラー
  # routesが合っていないのが原因なので、書き換えないといけない。
  # 以下のコードを追加する。このコードは既存のログアウトルーティングに上書きされる。
  # ※application.html.erb側の変更は特になし
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # //2020/12/25 add S.Shimada【解決策】deviseのログアウト機能でのエラー
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # 2020/12/25 add S.Shimada バリデーションを設定
  validates :name, presence: true
  validates :profile, presence: true
  validates :occupation, presence: true
  # validates :position, presence: true
  # //2020/12/25 add S.Shimada バリデーションを設定

  # 2020/12/28 add S.Shimada Userモデルにアソシエーション記述した
  # has_many :prototypes
  # //2020/12/28 add S.Shimada Userモデルにアソシエーション記述した
  
  # 2020/12/29 add S.Shimada コメント機能の追加によりアソシエーションを追記
  # has_many :prototypes, through: :comments
  # ↑に設定すると下記のエラーが発生する。
  # ActiveRecord::HasManyThroughAssociationNotFoundError in UsersController#show
  # Could not find the association :comments in model User
  # 【結論】そもそも多：多の関係じゃないため、throughの定義は不要であった。
  has_many :comments
  # //2020/12/29 add S.Shimada コメント機能の追加によりアソシエーションを追記

  # いいね機能実装用のアソシエーション
  has_many :prototypes, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_prototypes, through: :likes, source: :prototype
  # ユーザーが投稿に対して、すでにいいねをしているのかどうかを
  # 判定することができるようにalready_liked?を定義します。
  def already_liked?(prototype)
    self.likes.exists?(prototype_id: prototype.id)
  end
  # //いいね機能実装用のアソシエーション
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :current_user_like_count
  # My-carDページ用に追加
  def new
    @user = User.find(current_user.id)
    # 最新の投稿順に並ぶよう一度投稿日順に取得し直す。
    @user_like = @user.liked_prototypes.order("created_at DESC")
  end
  # //My-carDページ用に追加
  # 2020/12/29 add S.Shimada
  # usersコントローラーにshowアクションを定義
  def show
    # usersコントローラーのshowアクションにインスタンス変数@userを定義した。
    # 且つ、Pathパラメータで送信されるID値で、Userモデルの特定のオブジェクトを取得するように記述し、
    # それを@userに代入した
    @user = User.find(params[:id])
    # ↓だと全ユーザーのデータが取れてしまう
    # @prototypes = Prototype.all
    @prototypes = @user.prototypes.order("created_at DESC")
  end
  # //2020/12/29 add S.Shimada

  private

  def current_user_like_count
    # ヘッダーのお気に入り枚数表示用
    if user_signed_in?
      @current_user_like_count = User.find(current_user.id)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{@user.name}さんのお気に入りカード一覧"%>
      </h2>
      <div class='item-contents'>
        <ul class='item-lists'>
          <% @user_like.each do |prototype| %>
          <%= link_to prototype_path(prototype.id) do %>
            <%# カテゴリー別にカードの色を変える %>
            <% if prototype.category_id == 2 %>
              <li class='list card_back card_color2'>
            <% elsif prototype.category_id == 3 %>
              <li class='list card_back card_color3'>
            <% elsif prototype.category_id == 6 %>
              <li class='list card_back card_color6'>
            <% elsif prototype.category_id == 9 %>
              <li class='list card_back card_color9'>
            <% else %>
              <li class='list card_back card_color'>
            <% end %>
            <%# //カテゴリー別にカードの色を変える %>
            <div class='item-img-content'>
              <%= image_tag prototype.image, class: "item-img" %>
            </div>
            <div class='item-info'>
              <div class='star-btn'>
                <%= "(#{I18n.l prototype.created_at, formats: :default})" %>
              </div>
              <p class='item-name'>
                <%= prototype.title %>
              </p>
              <p class='item-name'>
              <%= link_to "by #{prototype.user.name}", "/users/#{prototype.user.id}", class: :prototype__user %>
              </p>
              <div class='star-btn-top'>
                <%= image_tag "category.png", class:"star-icon" %>
                <span class='star-count-top'><%= prototype.category.name %></span>
              </div>
              <div class='item-price'>
                <div class='star-btn-top'>
                  <%= image_tag "count.png", class:"star-icon" %>
                  <span class='star-count-top'><%= prototype.impressions_count %></span>
                </div>
                <div class='star-btn-top'>
                  <%= image_tag "good.png", class:"star-icon" %>
                  <span class='star-count-top'><%= prototype.liked_users.count %></span>
                </div>
              </div>
            </div>
          </li>
          <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{@user.name}さんの情報"%>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">プロフィール</th>
            <td class="table__col2"><%= "#{@user.profile}" %></td>
          </tr>
          <tr>
            <th class="table__col1">ジャンル</th>
            <td class="table__col2"><%= "#{@user.occupation}" %></td>
          </tr>
          <tr>
            <th class="table__col1">Twitter</th>
            <td class="table__col2">
            <a href=<%= "#{@user.position}" %> class="twitter-follow-button" data-show-count="false"></a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
            </td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= "#{@user.name}さんのVoice--carD一覧"%>
      </h2>
      <div class='item-contents'>
        <ul class='item-lists'>
          <%# 部分テンプレートでそのユーザーが投稿したプロトタイプ投稿一覧を表示する %>
          <%= render partial: "prototypes/prototype", collection: @prototypes %>
        </ul>
      </div>
    </div>
  </div>
</div>