config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'prototypes/index'
  root to: "prototypes#index"
  # 2020/12/28 add S.Shimada
  # resourcesを用いて、上記で設定したnewアクションとcreateアクションに対するルーティングをroutes.rbに記述した。
  # resources :prototypes, only: [:new, :create,]
  # showアクションのルーティングを設定
  # resources :prototypes, only: [:new, :create, :show]
  # edit、updateアクションのルーティングを設定
  # resources :prototypes, only: [:new, :create, :show, :edit, :update]
  # 削除機能用のルーティングを設定
  # resources :prototypes, only: [:new, :create, :show, :edit, :update, :destroy]
  # //2020/12/28 add S.Shimada

  # 2020/12/29 add S.Shimada コメント機能のルーティングを設定
  resources :prototypes, only: [:new, :create, :show, :edit, :update, :destroy] do
    # doとendで挟むことにより、ルーティングの記述をネストさせることができました。
    # この記述によって、「ある投稿に対してのコメント」という親子関係を表現したパスが、
    # コメント投稿に必要なリクエストのパスになります。
    resources :comments, only: :create
    # いいね機能実装用のルーティング
    resources :likes, only: [:create, :destroy]
    # 検索機能の実装
    collection do
      get 'search'
    end
  end
  # //2020/12/29 add S.Shimada コメント機能のルーティングを設定

  # 2020/12/29 add S.Shimada ユーザーに関するshowアクションのルーティングを設定
  # My-carDページ用に追加
  resources :users, only: [:new, :edit, :show]
  # //2020/12/29 add S.Shimada ユーザーに関するshowアクションのルーティングを設定

  # 2020/12/25 add S.Shimada【解決策】deviseのログアウト機能でのエラー
  # routesが合っていないのが原因なので、書き換えないといけない。
  # 以下のコードを追加する。このコードは既存のログアウトルーティングに上書きされる。
  # ※application.html.erb側の変更は特になし
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # //2020/12/25 add S.Shimada【解決策】deviseのログアウト機能でのエラー
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content="no-cache" name="turbolinks-cache-control">
    <meta http-equiv="cache-control" content="no-store">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Voice--carD</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Economica:700" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Yusei+Magic&display=swap" rel="stylesheet">  
  </head>

  <body>
  <div class="btn-group mt-2 mb-4" role="group" aria-label="actionButtons">
  </div>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
          <div class="nav__right">
              <% if user_signed_in? %>
                <%= form_with(url: search_prototypes_path, local: true, method: :get, class: "search-form") do |form| %>
                  <%= form.text_field :keyword, placeholder: "キーワードから探す", class: "input-box" %>
                  <button class="search-button">
                  <%= image_tag "search.png", class:"search-icon" %>
                  </button>
                <% end %>
              <% end %>
          </div>
        </div>
        <div class="nav">
          <div class="nav__left">
            <ul class='lists-left'>
              <% if user_signed_in? %>
              <%# この制御がないとログアウトカレントユーザーが無いのでエラーが出る %>
              <li><%= link_to 'カテゴリー', "#", class: "category-list" %></li>
              <li><%= link_to 'お気に入り', new_user_path, class: "brand-list" %>
                <%= "(#{@current_user_like_count.likes.count})" %>
              </li>
              <% end %>
            </ul>
          </div>
          <% if user_signed_in? %>
          <%# ログインしているときは以下を表示する %>
            <div class="nav__right">
              <ul class='lists-right'>
                <li><%= link_to "ようこそ、#{current_user.name}さん♪", "/users/#{current_user.id}", class: :nav__login %></li>
              </ul>
            </div>
            <div class="nav__right">
              <ul class='lists-right'>
                <li><%= link_to "ログアウト", destroy_user_session_path, class: :nav__logout %></li>
                <li><%= link_to "Voice--carD作成", new_prototype_path, class: :nav__btn %></li>
              </ul>
            </div>
          <%# // ログインしているときは上記を表示する %>
          <% else %>
          <%# ログインしていないときは以下を表示する %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <%# // ログインしていないときは上記を表示する %>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © Voice--carD All rights reserved.</p>
    </footer>
  </body>
</html>